

services:
  db:
    image: postgres
    container_name: flooring_db_prod
    restart: always
    environment:
      
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: flooring_db
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: